### ISSUE TITLE
Ctrl + C not working

### ISSUE THREAD

**Issue by vijaykerure** [hmenyus/node-calls-python#13]
When try to stop running Node (express) server, it won't works.

**Comment by vijaykerure** [comment]
Operating System: Windows 10
Node Version: v16.13.1
NPM Version: 8.1.2

**Comment by vijaykerure** [comment]
@hmenyus  Could you please look into this?

**Comment by hmenyus** [comment]
fixed in 1.5.4, tested on windows and linux as well

**Comment by vijaykerure** [comment]
Thank you very much @hmenyus
