### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by maxah** [hmenyus/node-calls-python#16]
System Linux 4.9.0-17-amd64
npm  v8.6.0
node -v v16.13.1
node-gyp -v v9.0.0
Python-3.6.13

**Comment by maxah** [comment]
[2022-04-27T13_13_00_396Z-debug-0.log](https://github.com/hmenyus/node-calls-python/files/8572450/2022-04-27T13_13_00_396Z-debug-0.log)

**Comment by hmenyus** [comment]
Please check if you have properlly installed python3-dev package and have python3-config in the PATH.
If yes, please attach the output of this command: python3-config --ldflags --embed
