### ISSUE TITLE
aws ec2 installation error:

### ISSUE THREAD

**Issue by Levshenkov** [hmenyus/node-calls-python#30]
Hi there.
I'm trying to install the latest 1.7.1 package on the AWS ec2 linux instance and get the following error:

>[ec2-user@ip-172-31-28-18 avs-deployment]$ npm i node-calls-python
>npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> font-manager@0.2.2 install /home/ec2-user/gitclones/avs-deployment/node_modules/font-manager
> node-gyp rebuild

>/home/ec2-user/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: line 5: ~/.nvm/versions/node/v14.20.0/lib/node_modules/node-gyp/bin/node-gyp.js: No such file or directory

> node-calls-python@1.7.1 install /home/ec2-user/gitclones/avs-deployment/node_modules/node-calls-python
> node-gyp rebuild

>home/ec2-user/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: line 5: ~/.nvm/versions/node/v14.20.0/lib/node_modules/node-gyp/bin/node-gyp.js: No such file or directory
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>npm WARN eslint-config-cheminfo@8.0.2 requires a peer of eslint@^8.16.0 but none is installed. You must install peer dependencies yourself.
>npm WARN eslint-config-cheminfo@8.0.2 requires a peer of eslint-plugin-jest@^26.4.6 but none is installed. You must install peer dependencies yourself.
>npm WARN eslint-config-cheminfo@8.0.2 requires a peer of eslint-plugin-jsdoc@^39.3.2 but none is installed. You must install peer dependencies yourself.
>npm WARN avs-deployment@1.19.0 No repository field.
>npm WARN avs-deployment@1.19.0 No license field.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: font-manager@0.2.2 (node_modules/font-manager):
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: font-manager@0.2.2 install: `node-gyp rebuild`
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

>npm ERR! code ELIFECYCLE
>npm ERR! syscall spawn
>npm ERR! file sh
>npm ERR! errno ENOENT
>npm ERR! node-calls-python@1.7.1 install: `node-gyp rebuild`
>npm ERR! spawn ENOENT
>npm ERR! 
>npm ERR! Failed at the node-calls-python@1.7.1 install script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
>npm ERR!     /home/ec2-user/.npm/_logs/2022-09-19T13_03_13_949Z-debug.log`

node-gyp.js is present in the ~/.nvm/versions/node/v14.20.0/lib/node_modules/node-gyp/bin/ dir.

**Comment by Levshenkov** [comment]
after set config path:
> npm config set node_gyp $(npm prefix -g)/lib/node_modules/node-gyp/bin/node-gyp.js

I get a new error:

>gyp: Call to 'python3-config --ldflags --embed' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
>gyp ERR! configure error 
>gyp ERR! stack Error: `gyp` failed with exit code: 1
>gyp ERR! stack     at ChildProcess.onCpExit (/home/ec2-user/.nvm/versions/node/v14.20.0/lib/node_modules/node->gyp/lib/configure.js:284:16)
>gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
>gyp ERR! System Linux 5.10.135-122.509.amzn2.x86_64
>gyp ERR! command "/home/ec2-user/.nvm/versions/node/v14.20.0/bin/node" "/home/ec2-user/.nvm/versions/node/v14.20.0/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
>gyp ERR! cwd /home/ec2-user/gitclones/avs-deployment/node_modules/node-calls-python
>gyp ERR! node -v v14.20.0
>gyp ERR! node-gyp -v v9.1.0
>gyp ERR! not ok

**Comment by hmenyus** [comment]
The problem is that python3.7-config does not have --embed option. I have released a fix in 1.7.2.
If that does not help, I recommend you to upgrade python version because  3.7 is about 4 years old.
