### ISSUE TITLE
Node Crashes on Nested Numpy Arrays

### ISSUE THREAD

**Issue by jasondalycan** [hmenyus/node-calls-python#31]
When traversing a nested Numpy array from within Node, node crashes if the parent item is referenced after an indexed item is referenced.  See the following example:

```
let ar = py.callSync(pyModule, "getArray", param);

// This works
for(let nestedArray of ar)
{  console.log(nestedArray[0]);
   console.log(nestedArray);
}

// This crashes node
for(let nestedArray of ar)
{  console.log(nestedArray);
   console.log(nestedArray[0]);
   console.log(nestedArray);
}
```

What is quite insteresting about this issue is that node does not throw an exception, it just exits.

I'm using Python 3.9.3, Node 16.15.1 on Windows 10.

**Comment by hmenyus** [comment]
I am not able to reproduce this with v16.17.1. Please attach getArray as well.
