### ISSUE TITLE
How to call library python

### ISSUE THREAD

**Issue by oNddleo** [hmenyus/node-calls-python#35]
I cant call another python library from node-calls-python.

**Comment by hmenyus** [comment]
Sorry, but I do not understand your problem. Could you attach code example?

**Comment by mccoysc** [comment]
the module work well in linux,but get crashed without any error info in gramine-sgx when call pyimport.

i found a debug info via gramine-sgx which said that "memory access error at address 0.

and also,i can run python by spawn("python").so the error must be caused by node-calls-python.
