### ISSUE TITLE
Amazon Linux 2 running problem

### ISSUE THREAD

**Issue by Abedk14** [hmenyus/node-calls-python#36]
after a successful installation of node-calls-python I wasn't able to run my code.

the code exist with segmentation fault after calling any python function using the package api.
I tried to use py.fixlink, but unfortunately I got the same error. 

I had to deep dive into the linkage process during the runtime. 

when I changed the search for libpython on index.js, everything works as it supposed to be 😄 

this the only change
index.js:18  :
if (file.match(/libpython**3**.*\.so/))

since Amazon Linux 2 had a build-in python2. and it's necessary for yum, the Interpreter will try to link to python2 first
 and this will cause segmentation fault

since the package requires python3, can you please change line the way I suggested or if you have a better way 

Thanks a lot 😄

**Comment by hmenyus** [comment]
Released the fix in 1.7.4. Thanks for reporting the issue.
