### ISSUE TITLE
run error without any error info in gramine-sgx

### ISSUE THREAD

**Issue by mccoysc** [hmenyus/node-calls-python#38]
the module work well in linux,but get crashed without any error info in gramine-sgx when loaded.

i found a debug info via gramine-sgx which said that "memory access error at address 0.

and also,i can run python by spawn("python").so the error must be caused by node-calls-python.

**Comment by mccoysc** [comment]
and also,in normal nodejs env,if i call some times,it also throw an error "SIGSEGV" and killed.
it seems that you have some memory error in code.

**Comment by mccoysc** [comment]
my code just like this: 

//only call this once.
py=new interpreter()



//may call many times:
pymodule=py.importSync("someMod")
pymodule.execSync(pymodule,params)
pymodule.evalSync(pymodule,parms)

at some time,the code cause nodejs crashed with SIGSEGV

**Comment by mccoysc** [comment]
i found that some time it crashed at evalSync with py code "data" and really,data is not defined in py file.

**Comment by mccoysc** [comment]
> Please attach a reproducable standalone example. What are your OS and node versions?

any code that run nodejs and require node-calls-python in gramine-sgx would repruduce the error.
about gramine-sgx:
https://github.com/gramineproject/gramine

**Comment by mccoysc** [comment]
![image](https://user-images.githubusercontent.com/18025276/203893189-81966549-2eb7-4d78-94eb-36e9e3beae02.png)

![image](https://user-images.githubusercontent.com/18025276/203893217-c5d8f61c-ae00-4719-858e-228a40728740.png)

**Comment by mccoysc** [comment]
i add some logs to your cpp code,and this is the logs:
![image](https://user-images.githubusercontent.com/18025276/203920528-c0a7f35d-7732-45c6-8354-8e2f623af096.png)
![image](https://user-images.githubusercontent.com/18025276/203920551-f38f3dd0-8748-4cc2-8272-410610dd3a41.png)

**Comment by mccoysc** [comment]
@hmenyus

**Comment by mccoysc** [comment]
and more:
if you create a worker,in the worker you require node-calls-python.
and call some api like importSync("import tensorflow") and execSync.
and then terminate the work.

and loop the above,maybe the node-calls-python would crash node process some time.

**Comment by hmenyus** [comment]
I cannot reproduce your problem with workers.

Regaring gramine: I do not have time to help you with this. Ubuntu, windows, mac work fine.

In the meantime I have added some improvements to some edge-cases in 1.7.5. Hopefully that will help you.
