### ISSUE TITLE
when i following example of Readme.md, but error occur  no attiribute!!

### ISSUE THREAD

**Issue by baaaaaaaaaaaaam** [hmenyus/node-calls-python#40]
![image](https://user-images.githubusercontent.com/57000871/206641744-b1c8c03d-672b-4b6a-883e-3994f43ee64b.png)

![image](https://user-images.githubusercontent.com/57000871/206641771-023b92c4-d912-46c8-b39a-2bf5b4dfd635.png)

![image](https://user-images.githubusercontent.com/57000871/206641962-7760be63-20b8-4522-b62f-7d6bd5a837ef.png)

**Comment by baaaaaaaaaaaaam** [comment]
why?

**Comment by hmenyus** [comment]
You may have another test.py somewhere in python search path. Use absolute path when importing otherwise python will iterate over sys.path to find the location of test.py

**Comment by ruizhi92** [comment]
I encountered the same problem. Changing filename "test.py" to other names doesn't help.

**Comment by hmenyus** [comment]
You have to use absolute path. Relative path works if the directory of the file is in sys.path. Please read this for details:
https://docs.python.org/3/library/sys_path_init.html
