### ISSUE TITLE
Spawn vs node-calls-python

### ISSUE THREAD

**Issue by apiel** [hmenyus/node-calls-python#45]
What are the advantage to use this library over spawn?

Is it better from a performance perspective? Is load python from the addon api more efficient than communicating with the python script through the spawn process?

Would be great to update the readme to explain why to use this library over spawn process.

**Comment by hmenyus** [comment]
updated the readme.

**Comment by apiel** [comment]
But how about to communicate with a python script through stdin/sdtout or even socket?
