### ISSUE TITLE
How to pass kwargs?

### ISSUE THREAD

**Issue by rioc0719** [hmenyus/node-calls-python#59]
Is there any way to pass kwargs to a function right now? I can't pass them using py.call since it only accepts positional arguments.

**Comment by hmenyus** [comment]
this is not doable right now. JS has no such concept, so I am not sure how to map JS arguments to kwargs.

**Comment by hmenyus** [comment]
https://github.com/hmenyus/node-calls-python/tree/master#passing-kwargs
You have install 1.8.0.
