### ISSUE TITLE
Module not found: Can't resolve './build/Release/nodecallspython' in NextJS server, or if the script is typescript

### ISSUE THREAD

**Issue by ericxl** [hmenyus/node-calls-python#68]
Ran into  ⨯ ./node_modules/node-calls-python/index.js:4:24
Module not found: Can't resolve './build/Release/nodecallspython'

with a default NextJS project. Sample attached.

It would work if I do the following two things
1. in package.json, add `"type": "module",`
2. change the route.ts (or all files that directly references `node-calls-python`) to javascript

To reproduce, download the following file and run `npm run dev` and go to http://localhost:3000. Thanks for this awesome repo!
[my-app.zip](https://github.com/hmenyus/node-calls-python/files/14015087/my-app.zip)

**Comment by garrettmaring** [comment]
bumping into this as well

**Comment by smoores-dev** [comment]
@josephjclark, I think you and @ericxl may have separate issues actually, with the same symptom. @ericxl's issue is, I suspect. caused by the fact that the `node-calls-python` index file doesn't specify a file extension for the `./build/Release/nodecallspython` path, which is strictly required in ESM (enabled by `"type": "module"`). Should be an easy enough fix, actually!

**Comment by smoores-dev** [comment]
Ah, sorry, it's actually even simpler than this: 

@ericxl, you simply need to "extern" `node-calls-python`, since its compiled node addon can't be bundled. With the Next.js app dir, that looks like adding this to your `next.config.js`:

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: [
      'node-calls-python'
    ]
  }
};

export default nextConfig;
``` 

Just tested this in your repro project and it worked :+1:

**Comment by hmenyus** [comment]
I agree, the problem is how next.js bundles native addons so the solution above could work.
 BTW, in 1.8.5 there is explicit support for es modules and I have also updated the readme with these.

**Comment by mabreyes** [comment]
Same issue. I want to use this within a react project. How do I implement this?
