### ISSUE TITLE
Support callback arguments

### ISSUE THREAD

**Issue by chfritz** [hmenyus/node-calls-python#92]
For the application I'm working on, it would be hugely beneficial if the arguments passed to `call` could include a callback that would be called at arbitrary times from the python code. Specifically we would like to use this for progress updates from a long-running python function.

Clearly there are some workaround, e.g., https://github.com/hmenyus/node-calls-python/issues/83#issuecomment-2101075120, or other, secondary communication mechanisms. But just like node-calls-python itself is motivated by the desire to avoid IPC and other such inter-process communication, it would be nice to be able to avoid the same for more fluent communication between python and node for the duration of the call.

**Comment by hmenyus** [comment]
Ok, noted. I will try to do something

**Comment by hmenyus** [comment]
Callbacks are now supported in 1.11.0. Please check this for details: https://github.com/hmenyus/node-calls-python?tab=readme-ov-file#passing-javascript-functions-to-python

**Comment by chfritz** [comment]
wow, that is super awesome! Thank you so much!

PS: works like charm!
